services:
  app:
    build:
      context: .
      target: app
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PASSWORD: rootpasswd
      DB_DATABASE: auto_val_db
      DB_USERNAME: app_user
    volumes:
      - ./:/var/www:cached
      - /var/www/vendor
      - /var/www/node_modules
      - tempdata:/var/www/storage/logs
      - tempdata:/var/www/storage/framework/cache
      - tempdata:/var/www/storage/framework/sessions
      - tempdata:/var/www/storage/framework/views
      - tempdata:/var/www/bootstrap/cache
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: auto_val_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: rootpasswd
      MYSQL_ROOT_PASSWORD: passwdroot
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      target: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/templates/default.conf.template:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  nodejs:
    build:
      context: .
      target: nodejs
    container_name: nodejs
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /var/www
    command: npm run watch
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules

volumes:
  mysql_data:
  node_modules:
  tempdata:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs