/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.update": [],
    "register": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "two-factor.login": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "sanctum.csrf-cookie": [],
    "welcome.index": [],
    "home.index": [],
    "cars-selling.index": [],
    "assistance.index": [],
    "stories.index": [],
    "stories.create": [],
    "stories.store": [],
    "gallery.index": [],
    "contact-us.index": [],
    "dashboard": []
}
}
export {};
